### ISSUE TITLE
Cannot read properties of undefined (reading 'sort')

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#233]
```
TypeError: Cannot read properties of undefined (reading 'sort')
    at https://bgmi.ricterz.me/assets/@generouted_react-router@1.12.0_react-router-dom@6.9.0_react@18.2.0_vite@4.2.1-0c22ba69.js:1:28359
    at Array.forEach (<anonymous>)
    at https://bgmi.ricterz.me/assets/@generouted_react-router@1.12.0_react-router-dom@6.9.0_react@18.2.0_vite@4.2.1-0c22ba69.js:1:28345
    at Object.useMemo (https://bgmi.ricterz.me/assets/react-dom@18.2.0_react@18.2.0-1ee5a4c8.js:14:25714)
    at u.useMemo (https://bgmi.ricterz.me/assets/react@18.2.0-04db4207.js:9:6062)
    at tr (https://bgmi.ricterz.me/assets/@generouted_react-router@1.12.0_react-router-dom@6.9.0_react@18.2.0_vite@4.2.1-0c22ba69.js:1:28263)
    at Bi (https://bgmi.ricterz.me/assets/react-dom@18.2.0_react@18.2.0-1ee5a4c8.js:14:19463)
    at ia (https://bgmi.ricterz.me/assets/react-dom@18.2.0_react@18.2.0-1ee5a4c8.js:16:43637)
    at ta (https://bgmi.ricterz.me/assets/react-dom@18.2.0_react@18.2.0-1ee5a4c8.js:16:39447)
    at tf (https://bgmi.ricterz.me/assets/react-dom@18.2.0_react@18.2.0-1ee5a4c8.js:16:39378)
```

返回的星期数据中 unknown 是 undefined 导致的问题

**Comment by kahosan** [comment]
解决晚了点，抱歉
